Repository CheeUp/CheeUp-FE, pull requests merged in 2025-01, with the labels that each got.

#29 채용공고 작성 페이지(1)
  src/App.tsx
  src/components/pages/recruit/new/index.tsx
  src/components/recruit/RecruitFilter.tsx
  src/components/recruit/calendar/CalendarNavigation.tsx
  src/components/recruit/calendar/DatePicker.tsx
  src/components/recruit/calendar/RecruitCalendar.tsx
  src/components/recruit/calendar/SmallCalendar.tsx
  src/components/recruit/new/RecruitForm.tsx
  src/components/ui/dropdown/Dropdown.tsx
  src/components/ui/dropdown/DropdownList.tsx
  src/components/ui/dropdown/LabeledDropdown.tsx
  src/components/ui/icons/ArrowIcon.tsx
  src/components/ui/icons/CalendarIcon.tsx
  src/hooks/useCalendar.ts
  src/hooks/useRecruitCalendar.tsx
  src/index.css
  tailwind.config.js
Labels: ✨ Feature

#35 📃 docs: 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/✅-test.md
  .github/ISSUE_TEMPLATE/✨-feat.md
  .github/ISSUE_TEMPLATE/🌏-deploy.md
  .github/ISSUE_TEMPLATE/🐛-fix.md
  .github/ISSUE_TEMPLATE/💄-style.md
  .github/ISSUE_TEMPLATE/📃-docs.md
  .github/ISSUE_TEMPLATE/🔨-refactor.md
  .github/ISSUE_TEMPLATE/🚚-chore.md
Labels: 📃 docs

#39 :bug: fix: 오류해결
  src/components/pages/mypage/Mypage.tsx
Labels: 🐛 fix

#37 ✨ feat: 채용공고 작성 페이지 모집 날짜 시간 추가
  src/components/recruit/calendar/DatePicker.tsx
  src/components/recruit/calendar/SmallCalendar.tsx
  src/components/recruit/new/RecruitForm.tsx
  src/util/date.ts
Labels: ✨ feat

#38 ✨ feat: 스크랩한 글, 공고,내 글 목록
  src/App.tsx
  src/components/layout/Sidebar.tsx
  src/components/mypage/MyPostList.tsx
  src/components/mypage/ProFileEditForm.tsx
  src/components/mypage/ProFileView.tsx
  src/components/mypage/ScrapList.tsx
  src/components/mypage/UserInfoCard.tsx
  src/components/pages/mypage/Mypage.tsx
  src/components/pages/mypage/index.tsx
  src/components/ui/post/PostCard.tsx
  src/mocks/data/postsdata.ts
  src/mocks/data/userdata.ts
Labels: ✨ feat
